version: '3.8'

name: payflow-manager

networks:
  backend:
    name: payflow-backend
    driver: bridge
  frontend:
    name: payflow-frontend
    driver: bridge

volumes:
  mysql_data:
    name: mysql_data

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - backend    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    restart: always

  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "5555:5555"    
    volumes:
      - ./cloud-conf:/cloud-conf
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=/cloud-conf
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=*
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://172.20.10.2:5555/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  eureka-service:
    build:
      context: ./eureka-discoveryservice
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://172.20.10.2:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=eureka-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - backend    
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://172.20.10.2:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  gateway-service:
    build:
      context: ./gatewayservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy    
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://172.20.10.2:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.20.10.2:8761/eureka/
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://172.20.10.2:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  auth-service:
    build:
      context: ./authentification-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_healthy   
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8087/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  produit-service:
    build:
      context: ./produit-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - backend    
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  facture-service:
    build:
      context: ./factureservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  reglement-service:
    build:
      context: ./reglement-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      config-service:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:5555
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8084/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  frontend:
    build:
      context: ./PayFlow_Manager
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      gateway-service:
        condition: service_healthy
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped